AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dice10k-serverless

  SAM Template for dice10k that has the DynamoDB table and Lambda
  functions on API Gateway needed to connect and play game.

Parameters:
  GameTableName:
    Type: String
    Default: 'dice10k_games'
    Description: (Required) The name of the DynamoDB table to store dice10k games.
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[0-9A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No special characters allowed.'
  PlayerTableName:
    Type: String
    Default: 'dice10k_players'
    Description: (Required) The name of the DynamoDB table to store dice10 players.
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[0-9A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No special characters allowed.'

Resources:
  DicekWebsocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: DicekWebsocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.message"
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DicekWebsocket
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectInteg
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref DicekWebsocket
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DicekWebsocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref DicekWebsocket
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations
  CreateRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DicekWebsocket
      RouteKey: creategame
      AuthorizationType: NONE
      OperationName: CreateRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref CreateInteg
  CreateInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref DicekWebsocket
      Description: Create Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateGameFunction.Arn}/invocations
  JoinRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DicekWebsocket
      RouteKey: joingame
      AuthorizationType: NONE
      OperationName: JoinRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref JoinInteg
  JoinInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref DicekWebsocket
      Description: Join Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JoinGameFunction.Arn}/invocations
  RollRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DicekWebsocket
      RouteKey: rolldice
      AuthorizationType: NONE
      OperationName: RollRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref RollInteg
  RollInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref DicekWebsocket
      Description: Roll Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RollDiceFunction.Arn}/invocations
  StartRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DicekWebsocket
      RouteKey: startgame
      AuthorizationType: NONE
      OperationName: StartRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref StartInteg
  StartInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref DicekWebsocket
      Description: Start Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StartGameFunction.Arn}/invocations
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    - DisconnectRoute
    - CreateRoute
    - JoinRoute
    - RollRoute
    - StartRoute
    Properties:
      ApiId: !Ref DicekWebsocket
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref DicekWebsocket
  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "name"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "name"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: False
      TableName: !Ref GameTableName
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: True
  PlayersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "connectionId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "connectionId"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: False
      TableName: !Ref PlayerTableName
  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: onconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs24.x
      Environment:
        Variables:
          PLAYER_TABLE_NAME: !Ref PlayerTableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref PlayerTableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DicekWebsocket}/*'
  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - DicekWebsocket
      - OnConnectFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com
  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ondisconnect/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs24.x
      Environment:
        Variables:
          PLAYER_TABLE_NAME: !Ref PlayerTableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref PlayerTableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DicekWebsocket}/*'
  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - DicekWebsocket
      - OnDisconnectFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com
  CreateGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: creategame/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs24.x
      Environment:
        Variables:
          PLAYER_TABLE_NAME: !Ref PlayerTableName
          GAME_TABLE_NAME: !Ref GameTableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref PlayerTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref GameTableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DicekWebsocket}/*'
  CreateGamePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - DicekWebsocket
      - CreateGameFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateGameFunction
      Principal: apigateway.amazonaws.com
  JoinGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: joingame/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs24.x
      Environment:
        Variables:
          PLAYER_TABLE_NAME: !Ref PlayerTableName
          GAME_TABLE_NAME: !Ref GameTableName
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref PlayerTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref GameTableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DicekWebsocket}/*'
  JoinGamePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - DicekWebsocket
      - JoinGameFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref JoinGameFunction
      Principal: apigateway.amazonaws.com
  RollDiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: rolldice/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs24.x
      Environment:
        Variables:
          PLAYER_TABLE_NAME: !Ref PlayerTableName
          GAME_TABLE_NAME: !Ref GameTableName
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref PlayerTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref GameTableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DicekWebsocket}/*'
  RollDicePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - DicekWebsocket
      - RollDiceFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RollDiceFunction
      Principal: apigateway.amazonaws.com
  StartGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: startgame/
      Handler: app.handler
      MemorySize: 256
      Runtime: nodejs24.x
      Environment:
        Variables:
          PLAYER_TABLE_NAME: !Ref PlayerTableName
          GAME_TABLE_NAME: !Ref GameTableName
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref PlayerTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref GameTableName
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${DicekWebsocket}/*'
  StartGamePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - DicekWebsocket
      - StartGameFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref StartGameFunction
      Principal: apigateway.amazonaws.com
Outputs:
  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value: !Join [ '', [ 'wss://', !Ref DicekWebsocket, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]
